listen = "0.0.0.0:7000"
tcp_listen = "0.0.0.0:7001"
lz4_listen = "0.0.0.0:7002"
db_path = "demo/state/gateway.db"
signing_sk = "demo/state/gateway-signing.key"
gateway_name = "~demo01"
public_urls = ["lz4tcp://127.0.0.1:7002"]
directory_url = "http://127.0.0.1:4000"
directory_pk = "OnF3Jh7tZ4o3g3bmUdgjTDa4qlMHN-2Q4RrJQD6K124"
